INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('round table', '11', '1k');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('wizards cup', '23', '21');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('one ring', '63', '1q');
INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('the fellowship', '04', '2d');


INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Kelly', 'Marie', 'mjordan1n@blog', 'USAs', 'crabs ave', 'mo', '(80848-6527');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Tracy', 'king', 'pkelley2c@blog', 'USA', '97636 5th Pass', 'mo', '546670-0937');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('brit brit', 'forest', 'britbrit@gblog', 'USA', 'london street', 'mo', '(319)309-1959');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('La', 'Dorothy', 'dkennedy23@blog', 'USA', 'paris street', 'mo', '(605)308-6131');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('Lord', 'Sean', 'lord@blog', 'USA', '6611 denmark Street', 'mo', '(463)415-7449');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('of', 'the', 'tings@blog', 'USA', ' sweden Avenue', 'mo', '(192)264-2329');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('harry', 'potter', 'hpr@blog', 'USA', ' france Drive', 'mo', '(647)544-4105');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('merlin', 'beard', 'beard@blog', 'USA', 'round table drive', 'kc', '(906)910-4569');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, ADDRESS, STATE, PHONE_NUMBER) VALUES('lady', 'gaga', 'shallow@blog', 'USA', '', 'mo', '(568)965-0021');




INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = ''), (SELECT GUEST_ID FROM GUEST WHERE LAST_NAME = ''), '09-1-2019');

